### ISSUE TITLE
Small modern version appears blurry on windows

### ISSUE THREAD

**Issue by happizy** [ful1e5/Bibata_Cursor#119]
<h1> HELP </h1>
![image_2022-10-05_120006791](https://user-images.githubusercontent.com/61943115/194034554-530123fa-0381-43ef-b794-e479b92d34e1.png)

**Comment by icorbrey** [comment]
Can confirm, I also have this issue.

**Comment by acidicneko** [comment]
The size is always fixed no matter what cursor size we use. Windows just scales up small, regular, large versions to same sizes. Small and regular are blurred due to scaling

**Comment by ful1e5** [comment]
I have changed the canvas size of the cursor in the `*-Small` packages. Since I don't have Windows, I have tested some third-party tools, but you can still try these packages and let me know if there is any issue.

### Packages
[Bibata-Modern-Amber-Windows.zip](https://github.com/ful1e5/Bibata_Cursor/files/9738406/Bibata-Modern-Amber-Windows.zip)
[Bibata-Modern-Classic-Windows.zip](https://github.com/ful1e5/Bibata_Cursor/files/9738407/Bibata-Modern-Classic-Windows.zip)
[Bibata-Modern-Ice-Windows.zip](https://github.com/ful1e5/Bibata_Cursor/files/9738408/Bibata-Modern-Ice-Windows.zip)
[Bibata-Original-Amber-Windows.zip](https://github.com/ful1e5/Bibata_Cursor/files/9738409/Bibata-Original-Amber-Windows.zip)
[Bibata-Original-Classic-Windows.zip](https://github.com/ful1e5/Bibata_Cursor/files/9738410/Bibata-Original-Classic-Windows.zip)
[Bibata-Original-Ice-Windows.zip](https://github.com/ful1e5/Bibata_Cursor/files/9738411/Bibata-Original-Ice-Windows.zip)

**Comment by happizy** [comment]
it works, they appear as intended now.
Thanks a lot.

**Comment by happizy** [comment]
oops

**Comment by stanio** [comment]
See also: https://github.com/ful1e5/Bibata_Cursor/issues/116#issuecomment-1364735595
