### ISSUE TITLE
No grabbing hand cursor

### ISSUE THREAD

**Issue by deathtrip** [ful1e5/Bibata_Cursor#87]
## Description of the problem
Right now there's no grabbing hand cursor, instead it's replaced with the "all-scroll" cursor, while the open hand "grab" cursor is still there. It feels pretty inconsistent when browsing pdf files. Not sure if it's an oversight or s design decision, as erlier bibata versions had the grabbing hand present. 

### Your Environment

| Operating System | Linux             |

**Comment by deathtrip** [comment]
so is it fixed in the new version of clickgen?

**Comment by ful1e5** [comment]
Yup, The `Hand` cursor's database is updated in **clickgen v1.1.8**. But clickgen is a [lock on v1.1.7](https://github.com/ful1e5/Bibata_Cursor/blob/8c3b0857dc55735f5ac472cd7e2fcbc69a08d989/setup.py#L14) in Bibata, Because of clickgen's new module & API structure. 

If you set a new version in `install_requires`, There is a **100%** chance of error inside the ***build***. So, wait until the merge request :slightly_smiling_face:
